-- Suggested SQL Patches
-- Generated by audit_agent.py
-- Run date: 2026-05-14T20:01:51.310162+00:00

-- Patch for anomaly A001
-- Patch for A001: Exclude failed transactions from marketing conversion totals.
-- Marketing conversions must require confirmed server completion to prevent
-- counting payment failures as revenue events.
CREATE OR REPLACE VIEW mart_reconciliation_corrected AS
SELECT
    *,
    -- Override marketing conversion flag: only count as conversion when server confirmed
    CASE
        WHEN conversion_definition_marketing AND NOT conversion_definition_finance
        THEN false  -- was a purchase_intent but server failed: not a real conversion
        ELSE conversion_definition_marketing
    END AS conversion_definition_marketing_corrected,
    -- Flag rows that were previously miscounted
    (conversion_definition_marketing AND NOT conversion_definition_finance) AS was_overcounted_by_marketing
FROM mart_reconciliation;

-- Patch for anomaly A002
-- Patch for A002: Tag dark transactions for attribution investigation.
-- Does not drop them -- they are real revenue. Adds a channel tag so
-- analysts can route them to an 'unattributed' bucket rather than ignoring them.
CREATE OR REPLACE VIEW stg_server_logs_with_channel AS
SELECT
    *,
    CASE
        WHEN client_event_id IS NOT NULL THEN 'client_tracked'
        ELSE 'unattributed'  -- dark transaction: no client SDK event
    END AS attribution_channel,
    client_event_id IS NULL AS is_dark_transaction
FROM stg_server_logs;

-- Patch for anomaly A003
-- Patch for A003: Add session continuity check to flag orphaned purchase_intents.
-- Until session_start events are implemented, this view identifies purchase_intents
-- that have no same-user page_view or add_to_cart within the prior 60 minutes,
-- which is a proxy for 'no preceding session signal'.
CREATE OR REPLACE VIEW client_events_session_check AS
WITH events AS (SELECT * FROM stg_client_events),
purchase_intents AS (SELECT * FROM events WHERE event_name = 'purchase_intent'),
preceding_activity AS (
    SELECT
        p.event_id,
        p.user_id,
        p.event_at,
        COUNT(e.event_id) AS preceding_event_count
    FROM purchase_intents p
    LEFT JOIN events e
        ON  e.user_id = p.user_id
        AND e.event_at < p.event_at
        AND e.event_at >= p.event_at - INTERVAL '60 minutes'
        AND e.event_name IN ('page_view', 'add_to_cart')
    GROUP BY p.event_id, p.user_id, p.event_at
)
SELECT
    p.*,
    COALESCE(pa.preceding_event_count, 0) > 0 AS has_preceding_session_activity,
    COALESCE(pa.preceding_event_count, 0)      AS preceding_event_count
FROM events p
LEFT JOIN preceding_activity pa ON p.event_id = pa.event_id
WHERE p.event_name = 'purchase_intent';

-- Patch for anomaly A004
-- Patch for A004: Revenue variance reconciliation view.
-- Surfaces the exact decomposition of the $17,606.65 gap for stakeholder reporting.
-- Use this as the source for executive dashboards instead of each source in isolation.
CREATE OR REPLACE VIEW revenue_reconciliation_summary AS
SELECT
    'finance_completed'          AS revenue_definition,
    COUNT(*)                     AS transaction_count,
    ROUND(SUM(server_amount), 2) AS total_revenue,
    'Server-side completed transactions only. Source of truth for financial reporting.' AS definition_note
FROM mart_reconciliation
WHERE conversion_definition_finance

UNION ALL

SELECT
    'marketing_purchase_intents' AS revenue_definition,
    COUNT(*)                     AS transaction_count,
    ROUND(SUM(COALESCE(client_reported_amount, 0)), 2) AS total_revenue,
    'Client-side purchase_intent events. Used for attribution only, not financial reporting.' AS definition_note
FROM mart_reconciliation
WHERE conversion_definition_marketing

UNION ALL

SELECT
    'variance_dark_revenue'      AS revenue_definition,
    COUNT(*)                     AS transaction_count,
    ROUND(SUM(server_amount), 2) AS total_revenue,
    'Completed server transactions with no client event. Finance sees this; marketing cannot attribute it.' AS definition_note
FROM mart_reconciliation
WHERE attribution_category = 'finance_only' AND conversion_definition_finance

UNION ALL

SELECT
    'variance_failed_but_tracked' AS revenue_definition,
    COUNT(*)                      AS transaction_count,
    ROUND(SUM(COALESCE(client_reported_amount, 0)), 2) AS total_revenue,
    'Marketing counted these as conversions but the payment failed. Finance correctly excludes them.' AS definition_note
FROM mart_reconciliation
WHERE attribution_category = 'marketing_only';

